// products.js - what each city actually SHIPS.
//
// Generated content, hand-corrected. The product taxonomy and the per-city
// export profiles were researched externally, then validated against
// data.js and repaired here: six products were referenced by cities but
// never defined, one whole category was duplicated under two names, and
// the GENERAL residual weights were scaled down (see GENERAL_SCALE note
// below) because as-authored they left 41.5% of ALL contracts as generic
// filler, which is the exact problem this file exists to fix.
//
// Every product maps to exactly one of economy.js's 7 TRUCK_TYPES. Every
// city name here is verified to exist in data.js's masterCities and to be
// a real city (tier > 0 - tier-0 junctions never originate a contract).
"use strict";

// name -> { truck, category }
export const PRODUCTS = {
    // --- Agriculture & Produce ---
    "Fresh Citrus Fruits": { truck: "REEFER", category: "Agriculture & Produce" },
    "Palletized Avocados": { truck: "REEFER", category: "Agriculture & Produce" },
    "Fresh Leafy Greens": { truck: "REEFER", category: "Agriculture & Produce" },
    "Washington Apples": { truck: "REEFER", category: "Agriculture & Produce" },
    "Bulk Potatoes": { truck: "REEFER", category: "Agriculture & Produce" },
    "Grains & Bulk Wheat": { truck: "DRYVAN", category: "Agriculture & Produce" },
    "Baled Hay & Alfalfa": { truck: "FLATBED", category: "Agriculture & Produce" },
    "Raw Almonds & Nuts": { truck: "DRYVAN", category: "Agriculture & Produce" },
    // --- Dairy ---
    "Bottled Milk": { truck: "REEFER", category: "Dairy" },
    "Bulk Cheese Wheels": { truck: "REEFER", category: "Dairy" },
    "Artisanal Butter Pallets": { truck: "REEFER", category: "Dairy" },
    "Ice Cream Tubs": { truck: "REEFER", category: "Dairy" },
    "Yogurt Containers": { truck: "REEFER", category: "Dairy" },
    // --- Meat, Poultry & Seafood ---
    "Flash-Frozen Beef Quarters": { truck: "REEFER", category: "Meat, Poultry & Seafood" },
    "Fresh Chicken Breasts": { truck: "REEFER", category: "Meat, Poultry & Seafood" },
    "Processed Pork Products": { truck: "REEFER", category: "Meat, Poultry & Seafood" },
    "Frozen Seafood": { truck: "REEFER", category: "Meat, Poultry & Seafood" },
    "Live Lobsters": { truck: "REEFER", category: "Meat, Poultry & Seafood" },
    // --- Timber & Paper ---
    "Raw Pine Logs": { truck: "FLATBED", category: "Timber & Paper" },
    "Milled Lumber Boards": { truck: "FLATBED", category: "Timber & Paper" },
    "Plywood Sheets": { truck: "FLATBED", category: "Timber & Paper" },
    "Heavy Paper Rolls": { truck: "FLATBED", category: "Timber & Paper" },
    "Corrugated Cardboard": { truck: "DRYVAN", category: "Timber & Paper" },
    // --- Crude Oil & Refined Fuel ---
    "Unrefined Crude Oil": { truck: "TANKER", category: "Crude Oil & Refined Fuel" },
    "Diesel Fuel": { truck: "TANKER", category: "Crude Oil & Refined Fuel" },
    "Unleaded Gasoline": { truck: "TANKER", category: "Crude Oil & Refined Fuel" },
    "Aviation Kerosene": { truck: "TANKER", category: "Crude Oil & Refined Fuel" },
    "Lubricating Oils": { truck: "TANKER", category: "Crude Oil & Refined Fuel" },
    // --- Petrochemicals & Chemicals ---
    "Industrial Solvents": { truck: "TANKER", category: "Petrochemicals & Chemicals" },
    "Liquid Fertilizer": { truck: "TANKER", category: "Petrochemicals & Chemicals" },
    "Sulfuric Acid": { truck: "TANKER", category: "Petrochemicals & Chemicals" },
    "Plastic Pellets & Resin": { truck: "DRYVAN", category: "Petrochemicals & Chemicals" },
    "Synthetic Polymers": { truck: "DRYVAN", category: "Petrochemicals & Chemicals" },
    // --- Mining & Coal ---
    "Crushed Coal": { truck: "FLATBED", category: "Mining & Coal" },
    "Iron Ore Pellets": { truck: "FLATBED", category: "Mining & Coal" },
    "Refined Copper Cathodes": { truck: "FLATBED", category: "Mining & Coal" },
    "Raw Silica Sand": { truck: "FLATBED", category: "Mining & Coal" },
    "Bulk Lithium Salts": { truck: "DRYVAN", category: "Mining & Coal" },
    "Oilfield Equipment": { truck: "FLATBED", category: "Mining & Coal" },
    "Gold Bullion": { truck: "TECH", category: "Mining & Coal" },
    "Phosphate Rock": { truck: "FLATBED", category: "Mining & Coal" },
    "Kaolin Clay": { truck: "FLATBED", category: "Mining & Coal" },
    // --- Steel & Metals ---
    "Hot-Rolled Steel Coils": { truck: "FLATBED", category: "Steel & Metals" },
    "Structural I-Beams": { truck: "FLATBED", category: "Steel & Metals" },
    "Rebar Bundles": { truck: "FLATBED", category: "Steel & Metals" },
    "Steel Pipe & Tubing": { truck: "FLATBED", category: "Steel & Metals" },
    "Sheet Metal Stock": { truck: "FLATBED", category: "Steel & Metals" },
    "Scrap Steel": { truck: "FLATBED", category: "Steel & Metals" },
    "Aluminum Ingots": { truck: "FLATBED", category: "Steel & Metals" },
    // --- Automotive ---
    "Finished Sedans & Coupes": { truck: "AUTO", category: "Automotive" },
    "Heavy-Duty Pickup Trucks": { truck: "AUTO", category: "Automotive" },
    "Machined Engine Blocks": { truck: "FLATBED", category: "Automotive" },
    "Stamped Auto Body Panels": { truck: "DRYVAN", category: "Automotive" },
    "Palletized Rubber Tires": { truck: "DRYVAN", category: "Automotive" },
    // --- Tech & Electronics ---
    "Server Rack Cabinets": { truck: "TECH", category: "Tech & Electronics" },
    "Semiconductor Wafers": { truck: "TECH", category: "Tech & Electronics" },
    "Telecommunications Switches": { truck: "TECH", category: "Tech & Electronics" },
    "Consumer Laptops & PCs": { truck: "TECH", category: "Tech & Electronics" },
    "High-End Smartphones": { truck: "TECH", category: "Tech & Electronics" },
    "Battery Packs": { truck: "TECH", category: "Tech & Electronics" },
    // --- Aerospace ---
    "Jet Engine Turbines": { truck: "FLATBED", category: "Aerospace" },
    "Fuselage Skin Panels": { truck: "FLATBED", category: "Aerospace" },
    "Avionics Control Systems": { truck: "TECH", category: "Aerospace" },
    "Landing Gear Struts": { truck: "FLATBED", category: "Aerospace" },
    "Aerospace Fasteners": { truck: "DRYVAN", category: "Aerospace" },
    // --- Pharma & Medical ---
    "Refrigerated Vaccines": { truck: "REEFER", category: "Pharma & Medical" },
    "MRI Machine Components": { truck: "TECH", category: "Pharma & Medical" },
    "Surgical Instruments": { truck: "TECH", category: "Pharma & Medical" },
    "Bottled Prescription Meds": { truck: "DRYVAN", category: "Pharma & Medical" },
    "Hospital Beds": { truck: "DRYVAN", category: "Pharma & Medical" },
    // --- Military ---
    "Munitions & Explosives": { truck: "MILITARY", category: "Military" },
    "Armored Vehicle Parts": { truck: "MILITARY", category: "Military" },
    "Tactical Rations / MREs": { truck: "MILITARY", category: "Military" },
    "Artillery Shells": { truck: "MILITARY", category: "Military" },
    "Unmanned Aerial Drones": { truck: "MILITARY", category: "Military" },
    "Classified Defense Tech": { truck: "MILITARY", category: "Military" },
    // --- Ports & Imports ---
    "Standard Shipping Containers": { truck: "DRYVAN", category: "Ports & Imports" },
    "Imported Electronics": { truck: "DRYVAN", category: "Ports & Imports" },
    "Bulk Foreign Textiles": { truck: "DRYVAN", category: "Ports & Imports" },
    "Imported Auto Parts": { truck: "DRYVAN", category: "Ports & Imports" },
    // --- Logistics & Express ---
    "Amazon Prime Parcels": { truck: "DRYVAN", category: "Logistics & Express" },
    "Overnight Express Envelopes": { truck: "DRYVAN", category: "Logistics & Express" },
    "E-Commerce Fulfillment": { truck: "DRYVAN", category: "Logistics & Express" },
    "LTL Mixed Pallets": { truck: "DRYVAN", category: "Logistics & Express" },
    "Priority Air Cargo": { truck: "DRYVAN", category: "Logistics & Express" },
};

// City -> [[productName, weight], ...]. "GENERAL" means ordinary dry
// freight off economy.js's GENERAL_CARGO_POOL. Weights are relative
// within a city and normalized at load; they do not need to sum to 100.
//
// GENERAL residuals were scaled by 0.42 from the researched values.
// Rationale, measured rather than guessed: at the original weights the
// projected fleet mix was 74.3% dry van - barely better than the 78.5%
// this replaced - because the residual alone accounted for 41.5% of all
// contracts. Scaling it lets the themed products actually show up.
export const CITY_EXPORTS = {
    "Abilene": [["Unmanned Aerial Drones", 15], ["LTL Mixed Pallets", 15], ["GENERAL", 29]],
    "Akron": [["Palletized Rubber Tires", 45], ["Synthetic Polymers", 25], ["GENERAL", 13]],
    "Albany": [["Semiconductor Wafers", 30], ["LTL Mixed Pallets", 15], ["GENERAL", 23]],
    "Albuquerque": [["Diesel Fuel", 25], ["E-Commerce Fulfillment", 15], ["GENERAL", 25]],
    "Allentown": [["Amazon Prime Parcels", 35], ["E-Commerce Fulfillment", 25], ["GENERAL", 17]],
    "Amarillo": [["Flash-Frozen Beef Quarters", 55], ["Processed Pork Products", 15], ["GENERAL", 13]],
    "Appleton": [["Heavy Paper Rolls", 45], ["Corrugated Cardboard", 25], ["GENERAL", 13]],
    "Atlanta": [["Amazon Prime Parcels", 35], ["E-Commerce Fulfillment", 25], ["Overnight Express Envelopes", 10], ["GENERAL", 13]],
    "Augusta": [["Heavy Paper Rolls", 30], ["Bulk Foreign Textiles", 15], ["GENERAL", 23]],
    "Austin": [["Semiconductor Wafers", 30], ["Server Rack Cabinets", 20], ["GENERAL", 21], ["High-End Smartphones", 10]],
    "Bakersfield": [["Unrefined Crude Oil", 45], ["Fresh Citrus Fruits", 20], ["Bulk Potatoes", 10], ["GENERAL", 11]],
    "Baltimore": [["Standard Shipping Containers", 35], ["Surgical Instruments", 20], ["GENERAL", 19]],
    "Bangor": [["Heavy Paper Rolls", 40], ["Raw Pine Logs", 15], ["GENERAL", 19]],
    "Barstow": [["LTL Mixed Pallets", 30], ["Armored Vehicle Parts", 15], ["GENERAL", 23]],
    "Baton Rouge": [["Industrial Solvents", 30], ["Synthetic Polymers", 20], ["Diesel Fuel", 20], ["GENERAL", 13], ["Plastic Pellets & Resin", 15]],
    "Beaumont": [["Diesel Fuel", 35], ["Standard Shipping Containers", 25], ["GENERAL", 17]],
    "Beckley": [["Crushed Coal", 55], ["Milled Lumber Boards", 15], ["GENERAL", 13]],
    "Billings": [["Flash-Frozen Beef Quarters", 30], ["Unleaded Gasoline", 25], ["GENERAL", 19]],
    "Binghamton": [["Consumer Laptops & PCs", 20], ["LTL Mixed Pallets", 15], ["GENERAL", 27]],
    "Birmingham": [["Hot-Rolled Steel Coils", 35], ["Structural I-Beams", 20], ["GENERAL", 19], ["Steel Pipe & Tubing", 15]],
    "Bismarck": [["Unleaded Gasoline", 30], ["Crushed Coal", 15], ["GENERAL", 23]],
    "Bloomington": [["Finished Sedans & Coupes", 25], ["E-Commerce Fulfillment", 15], ["GENERAL", 25]],
    "Boise": [["Consumer Laptops & PCs", 20], ["Bulk Potatoes", 25], ["GENERAL", 23]],
    "Boston": [["Refrigerated Vaccines", 25], ["Server Rack Cabinets", 20], ["GENERAL", 23]],
    "Bozeman": [["Consumer Laptops & PCs", 20], ["Server Rack Cabinets", 15], ["GENERAL", 27]],
    "Brownsville": [["Standard Shipping Containers", 30], ["Aerospace Fasteners", 20], ["GENERAL", 21]],
    "Buffalo": [["Heavy-Duty Pickup Trucks", 30], ["LTL Mixed Pallets", 20], ["GENERAL", 21]],
    "Butte": [["Refined Copper Cathodes", 45], ["Raw Silica Sand", 15], ["GENERAL", 17]],
    "Casper": [["Unrefined Crude Oil", 45], ["MRI Machine Components", 10], ["GENERAL", 19]],
    "Cedar Rapids": [["Grains & Bulk Wheat", 40], ["Synthetic Polymers", 15], ["GENERAL", 19], ["Liquid Fertilizer", 20]],
    "Champaign": [["Server Rack Cabinets", 25], ["Grains & Bulk Wheat", 15], ["GENERAL", 25]],
    "Charleston SC": [["Standard Shipping Containers", 35], ["Finished Sedans & Coupes", 25], ["GENERAL", 17]],
    "Charleston WV": [["Industrial Solvents", 35], ["Sulfuric Acid", 25], ["GENERAL", 17]],
    "Charlotte": [["LTL Mixed Pallets", 30], ["Diesel Fuel", 15], ["GENERAL", 23]],
    "Chattanooga": [["LTL Mixed Pallets", 40], ["Amazon Prime Parcels", 20], ["GENERAL", 17]],
    "Cheyenne": [["LTL Mixed Pallets", 35], ["Server Rack Cabinets", 15], ["GENERAL", 21]],
    "Chicago": [["E-Commerce Fulfillment", 25], ["LTL Mixed Pallets", 20], ["Hot-Rolled Steel Coils", 10], ["GENERAL", 19]],
    "Cincinnati": [["LTL Mixed Pallets", 25], ["Jet Engine Turbines", 20], ["GENERAL", 23]],
    "Clarksville": [["Tactical Rations / MREs", 25], ["LTL Mixed Pallets", 15], ["GENERAL", 25]],
    "Cleveland": [["Hot-Rolled Steel Coils", 30], ["Surgical Instruments", 20], ["GENERAL", 21]],
    "Coeur dAlene": [["Raw Pine Logs", 30], ["Milled Lumber Boards", 20], ["GENERAL", 21]],
    "Colorado Springs": [["Avionics Control Systems", 20], ["Unmanned Aerial Drones", 15], ["GENERAL", 27]],
    "Columbia": [["Bulk Foreign Textiles", 25], ["Finished Sedans & Coupes", 15], ["GENERAL", 25]],
    "Columbia MO": [["Grains & Bulk Wheat", 20], ["Refrigerated Vaccines", 15], ["GENERAL", 27]],
    "Columbus": [["E-Commerce Fulfillment", 35], ["Amazon Prime Parcels", 25], ["GENERAL", 17]],
    "Corpus Christi": [["Unrefined Crude Oil", 30], ["Standard Shipping Containers", 25], ["GENERAL", 19]],
    "Dallas": [["Server Rack Cabinets", 20], ["E-Commerce Fulfillment", 20], ["GENERAL", 25]],
    "Danbury": [["Bottled Prescription Meds", 35], ["Refrigerated Vaccines", 15], ["GENERAL", 21]],
    "Davenport": [["Machined Engine Blocks", 30], ["Artillery Shells", 15], ["GENERAL", 23]],
    "Dayton": [["Jet Engine Turbines", 35], ["LTL Mixed Pallets", 25], ["GENERAL", 17]],
    "Decatur": [["Jet Engine Turbines", 25], ["LTL Mixed Pallets", 15], ["GENERAL", 25]],
    "Denton": [["LTL Mixed Pallets", 35], ["Amazon Prime Parcels", 25], ["GENERAL", 17]],
    "Denver": [["Aerospace Fasteners", 20], ["Telecommunications Switches", 20], ["GENERAL", 25]],
    "Des Moines": [["Baled Hay & Alfalfa", 25], ["Grains & Bulk Wheat", 20], ["GENERAL", 23]],
    "Detroit": [["Finished Sedans & Coupes", 35], ["Machined Engine Blocks", 20], ["Stamped Auto Body Panels", 15], ["GENERAL", 13]],
    "Dickinson": [["Unrefined Crude Oil", 70], ["GENERAL", 13]],
    "Duluth": [["Iron Ore Pellets", 35], ["Heavy Paper Rolls", 25], ["GENERAL", 17]],
    "Eau Claire": [["Consumer Laptops & PCs", 20], ["LTL Mixed Pallets", 20], ["GENERAL", 25]],
    "Edison": [["Amazon Prime Parcels", 40], ["E-Commerce Fulfillment", 35], ["GENERAL", 11]],
    "El Paso": [["Unleaded Gasoline", 35], ["Imported Auto Parts", 25], ["GENERAL", 17]],
    "Elko": [["Gold Bullion", 30], ["Crushed Coal", 15], ["GENERAL", 23]],
    "Ellensburg": [["Baled Hay & Alfalfa", 40], ["GENERAL", 25]],
    "Erie": [["Machined Engine Blocks", 30], ["Synthetic Polymers", 25], ["GENERAL", 19]],
    "Eugene": [["Milled Lumber Boards", 40], ["Plywood Sheets", 20], ["GENERAL", 17]],
    "Eureka": [["Raw Pine Logs", 40], ["Standard Shipping Containers", 20], ["GENERAL", 17]],
    "Evansville": [["Finished Sedans & Coupes", 35], ["Standard Shipping Containers", 15], ["GENERAL", 21]],
    "Everett": [["Fuselage Skin Panels", 45], ["Aerospace Fasteners", 20], ["GENERAL", 15], ["Landing Gear Struts", 15]],
    "Fargo": [["Consumer Laptops & PCs", 20], ["Grains & Bulk Wheat", 30], ["GENERAL", 21]],
    "Fayetteville": [["Tactical Rations / MREs", 35], ["Munitions & Explosives", 20], ["GENERAL", 19]],
    "Fayetteville AR": [["E-Commerce Fulfillment", 40], ["Amazon Prime Parcels", 20], ["GENERAL", 17]],
    "Flint": [["Machined Engine Blocks", 35], ["Stamped Auto Body Panels", 25], ["GENERAL", 17]],
    "Florence": [["Bottled Prescription Meds", 35], ["Hospital Beds", 15], ["GENERAL", 21]],
    "Fort Collins": [["Grains & Bulk Wheat", 20], ["Consumer Laptops & PCs", 15], ["GENERAL", 27]],
    "Fort Lauderdale": [["Server Rack Cabinets", 20], ["LTL Mixed Pallets", 20], ["GENERAL", 25]],
    "Fort Myers": [["LTL Mixed Pallets", 25], ["Fresh Citrus Fruits", 15], ["GENERAL", 25]],
    "Fort Smith": [["LTL Mixed Pallets", 35], ["Synthetic Polymers", 15], ["GENERAL", 21]],
    "Fort Stockton": [["Unrefined Crude Oil", 70], ["Unleaded Gasoline", 15], ["GENERAL", 6]],
    "Fort Wayne": [["LTL Mixed Pallets", 35], ["Synthetic Polymers", 15], ["GENERAL", 21]],
    "Fort Worth": [["Fuselage Skin Panels", 25], ["Flash-Frozen Beef Quarters", 20], ["GENERAL", 23]],
    "Fresno": [["Fresh Citrus Fruits", 40], ["Fresh Leafy Greens", 30], ["GENERAL", 13], ["Raw Almonds & Nuts", 15]],
    "Gadsden": [["Hot-Rolled Steel Coils", 35], ["Bulk Foreign Textiles", 15], ["GENERAL", 21]],
    "Gainesville": [["Surgical Instruments", 25], ["Bottled Prescription Meds", 15], ["GENERAL", 25]],
    "Gallup": [["Refined Copper Cathodes", 20], ["Diesel Fuel", 20], ["GENERAL", 25]],
    "Galveston": [["Standard Shipping Containers", 30], ["Bottled Prescription Meds", 15], ["GENERAL", 23]],
    "Gary": [["Hot-Rolled Steel Coils", 50], ["Sheet Metal Stock", 20], ["GENERAL", 13], ["Steel Pipe & Tubing", 15]],
    "Gillette": [["Crushed Coal", 55], ["Diesel Fuel", 15], ["GENERAL", 13]],
    "Grand Forks": [["Unmanned Aerial Drones", 20], ["Grains & Bulk Wheat", 25], ["GENERAL", 23]],
    "Grand Junction": [["Unrefined Crude Oil", 30], ["Fresh Citrus Fruits", 10], ["GENERAL", 25]],
    "Grand Rapids": [["LTL Mixed Pallets", 25], ["Hospital Beds", 15], ["GENERAL", 25]],
    "Great Falls": [["Grains & Bulk Wheat", 35], ["Tactical Rations / MREs", 10], ["GENERAL", 23]],
    "Green Bay": [["Heavy Paper Rolls", 45], ["Corrugated Cardboard", 25], ["GENERAL", 13], ["Bulk Cheese Wheels", 15]],
    "Greensboro": [["Bulk Foreign Textiles", 30], ["Jet Engine Turbines", 15], ["GENERAL", 23]],
    "Greenville": [["Heavy-Duty Pickup Trucks", 30], ["Stamped Auto Body Panels", 15], ["GENERAL", 23]],
    "Hagerstown": [["LTL Mixed Pallets", 40], ["Aerospace Fasteners", 15], ["GENERAL", 19]],
    "Harrisburg": [["Amazon Prime Parcels", 30], ["Hot-Rolled Steel Coils", 15], ["GENERAL", 23]],
    "Hartford": [["Jet Engine Turbines", 30], ["E-Commerce Fulfillment", 15], ["GENERAL", 23]],
    "Hattiesburg": [["Tactical Rations / MREs", 20], ["LTL Mixed Pallets", 15], ["GENERAL", 27]],
    "Hays": [["Grains & Bulk Wheat", 40], ["Unrefined Crude Oil", 25], ["GENERAL", 15]],
    "Hermiston": [["LTL Mixed Pallets", 35], ["Baled Hay & Alfalfa", 25], ["GENERAL", 17]],
    "Houlton": [["Raw Pine Logs", 35], ["Bulk Potatoes", 30], ["GENERAL", 15]],
    "Houston": [["Diesel Fuel", 25], ["Aviation Kerosene", 15], ["Standard Shipping Containers", 20], ["Aerospace Fasteners", 10], ["GENERAL", 13], ["Lubricating Oils", 10]],
    "Huntsville": [["Fuselage Skin Panels", 30], ["Unmanned Aerial Drones", 20], ["GENERAL", 21]],
    "Idaho Falls": [["Bulk Potatoes", 35], ["Grains & Bulk Wheat", 20], ["GENERAL", 19]],
    "Indianapolis": [["Refrigerated Vaccines", 25], ["Bottled Prescription Meds", 20], ["LTL Mixed Pallets", 15], ["GENERAL", 17]],
    "Jackson": [["Finished Sedans & Coupes", 30], ["LTL Mixed Pallets", 20], ["GENERAL", 21]],
    "Jacksonville": [["Standard Shipping Containers", 35], ["LTL Mixed Pallets", 25], ["GENERAL", 17]],
    "Joliet": [["LTL Mixed Pallets", 40], ["Diesel Fuel", 20], ["GENERAL", 17]],
    "Joplin": [["LTL Mixed Pallets", 30], ["Bulk Lithium Salts", 15], ["GENERAL", 23]],
    "Kalamazoo": [["Refrigerated Vaccines", 35], ["Bottled Prescription Meds", 25], ["GENERAL", 17]],
    "Kansas City": [["Finished Sedans & Coupes", 30], ["Heavy-Duty Pickup Trucks", 15], ["LTL Mixed Pallets", 15], ["GENERAL", 17]],
    "Kearney": [["Grains & Bulk Wheat", 35], ["Baled Hay & Alfalfa", 15], ["GENERAL", 21]],
    "Kennewick": [["Diesel Fuel", 25], ["Fresh Leafy Greens", 15], ["GENERAL", 25]],
    "Killeen": [["Armored Vehicle Parts", 35], ["Tactical Rations / MREs", 20], ["GENERAL", 19]],
    "Kingsport": [["Industrial Solvents", 30], ["Heavy Paper Rolls", 30], ["GENERAL", 17]],
    "Knoxville": [["Aluminum Ingots", 35], ["LTL Mixed Pallets", 20], ["GENERAL", 19]],
    "Lafayette": [["Diesel Fuel", 25], ["Oilfield Equipment", 15], ["GENERAL", 25]],
    "Lake Charles": [["Industrial Solvents", 40], ["Unleaded Gasoline", 30], ["GENERAL", 13], ["Plastic Pellets & Resin", 12]],
    "Lakeland": [["E-Commerce Fulfillment", 35], ["Amazon Prime Parcels", 25], ["GENERAL", 17]],
    "Lansing": [["Finished Sedans & Coupes", 35], ["Stamped Auto Body Panels", 20], ["GENERAL", 19]],
    "Laredo": [["Imported Auto Parts", 35], ["Standard Shipping Containers", 35], ["GENERAL", 13]],
    "Las Cruces": [["Fresh Citrus Fruits", 25], ["Aerospace Fasteners", 15], ["GENERAL", 25]],
    "Las Vegas": [["LTL Mixed Pallets", 30], ["Amazon Prime Parcels", 20], ["GENERAL", 21]],
    "Lawton": [["Palletized Rubber Tires", 35], ["Munitions & Explosives", 15], ["GENERAL", 21]],
    "Lexington": [["Finished Sedans & Coupes", 25], ["Bottled Milk", 15], ["GENERAL", 25]],
    "Lincoln": [["E-Commerce Fulfillment", 25], ["Grains & Bulk Wheat", 15], ["GENERAL", 25]],
    "Little Rock": [["Aerospace Fasteners", 25], ["LTL Mixed Pallets", 15], ["GENERAL", 25]],
    "Long Beach": [["Standard Shipping Containers", 45], ["Diesel Fuel", 15], ["GENERAL", 17]],
    "Los Angeles": [["Standard Shipping Containers", 35], ["Imported Electronics", 15], ["Consumer Laptops & PCs", 10], ["GENERAL", 17]],
    "Louisville": [["Overnight Express Envelopes", 35], ["Priority Air Cargo", 25], ["Finished Sedans & Coupes", 10], ["GENERAL", 13]],
    "Lubbock": [["Grains & Bulk Wheat", 40], ["Baled Hay & Alfalfa", 20], ["GENERAL", 17]],
    "Lynchburg": [["E-Commerce Fulfillment", 20], ["LTL Mixed Pallets", 15], ["GENERAL", 27]],
    "Macon": [["Kaolin Clay", 30], ["Milled Lumber Boards", 15], ["GENERAL", 23]],
    "Madison": [["Server Rack Cabinets", 20], ["Refrigerated Vaccines", 20], ["GENERAL", 25]],
    "McAllen": [["Fresh Citrus Fruits", 45], ["Imported Electronics", 20], ["GENERAL", 15]],
    "Medford": [["Washington Apples", 40], ["GENERAL", 25]],
    "Melbourne": [["Avionics Control Systems", 35], ["Server Rack Cabinets", 15], ["GENERAL", 21]],
    "Memphis": [["Overnight Express Envelopes", 40], ["Priority Air Cargo", 25], ["Surgical Instruments", 10], ["GENERAL", 11]],
    "Miami": [["Standard Shipping Containers", 35], ["Imported Electronics", 20], ["GENERAL", 19]],
    "Midland": [["Unrefined Crude Oil", 85], ["GENERAL", 6]],
    "Miles City": [["Flash-Frozen Beef Quarters", 40], ["GENERAL", 25]],
    "Milwaukee": [["LTL Mixed Pallets", 25], ["Machined Engine Blocks", 15], ["GENERAL", 25]],
    "Minneapolis": [["E-Commerce Fulfillment", 30], ["Surgical Instruments", 15], ["GENERAL", 23]],
    "Minot": [["Unrefined Crude Oil", 40], ["Grains & Bulk Wheat", 20], ["GENERAL", 17]],
    "Missoula": [["Raw Pine Logs", 35], ["Milled Lumber Boards", 25], ["GENERAL", 17]],
    "Mobile": [["Jet Engine Turbines", 30], ["Standard Shipping Containers", 25], ["GENERAL", 19]],
    "Modesto": [["Baled Hay & Alfalfa", 35], ["Fresh Citrus Fruits", 25], ["GENERAL", 17], ["Raw Almonds & Nuts", 20]],
    "Monterey": [["Fresh Leafy Greens", 40], ["Frozen Seafood", 20], ["GENERAL", 17]],
    "Montgomery": [["Finished Sedans & Coupes", 30], ["Tactical Rations / MREs", 15], ["GENERAL", 23]],
    "Morgantown": [["Crushed Coal", 40], ["Server Rack Cabinets", 10], ["GENERAL", 21]],
    "Nashville": [["Finished Sedans & Coupes", 25], ["LTL Mixed Pallets", 25], ["GENERAL", 21]],
    "New Haven": [["Refrigerated Vaccines", 25], ["Surgical Instruments", 15], ["GENERAL", 25]],
    "New Orleans": [["Frozen Seafood", 30], ["Standard Shipping Containers", 30], ["GENERAL", 17]],
    "New York": [["Imported Electronics", 25], ["Standard Shipping Containers", 20], ["Overnight Express Envelopes", 15], ["GENERAL", 17]],
    "Newark": [["Standard Shipping Containers", 40], ["Priority Air Cargo", 20], ["LTL Mixed Pallets", 15], ["GENERAL", 11]],
    "Nogales": [["Fresh Citrus Fruits", 40], ["Imported Auto Parts", 25], ["GENERAL", 15]],
    "Norfolk": [["Standard Shipping Containers", 35], ["Munitions & Explosives", 20], ["GENERAL", 19]],
    "North Platte": [["LTL Mixed Pallets", 25], ["Grains & Bulk Wheat", 25], ["GENERAL", 21]],
    "Oakland": [["Standard Shipping Containers", 40], ["LTL Mixed Pallets", 25], ["GENERAL", 15]],
    "Ocala": [["LTL Mixed Pallets", 35], ["E-Commerce Fulfillment", 20], ["GENERAL", 19]],
    "Odessa": [["Unrefined Crude Oil", 70], ["LTL Mixed Pallets", 15], ["GENERAL", 6]],
    "Ogden": [["LTL Mixed Pallets", 35], ["Standard Shipping Containers", 20], ["GENERAL", 19]],
    "Oklahoma City": [["Diesel Fuel", 25], ["Aerospace Fasteners", 20], ["GENERAL", 23]],
    "Olympia": [["Raw Pine Logs", 35], ["Milled Lumber Boards", 25], ["GENERAL", 17]],
    "Omaha": [["Flash-Frozen Beef Quarters", 45], ["Processed Pork Products", 15], ["GENERAL", 17]],
    "Orlando": [["Priority Air Cargo", 25], ["LTL Mixed Pallets", 25], ["GENERAL", 21]],
    "Panama City": [["Standard Shipping Containers", 30], ["Armored Vehicle Parts", 15], ["GENERAL", 23]],
    "Pendleton": [["Grains & Bulk Wheat", 35], ["Baled Hay & Alfalfa", 20], ["GENERAL", 19]],
    "Pensacola": [["Jet Engine Turbines", 25], ["Tactical Rations / MREs", 15], ["GENERAL", 25]],
    "Peoria": [["Baled Hay & Alfalfa", 20], ["LTL Mixed Pallets", 20], ["GENERAL", 25]],
    "Petersburg": [["Bottled Prescription Meds", 30], ["LTL Mixed Pallets", 25], ["GENERAL", 19]],
    "Philadelphia": [["Refrigerated Vaccines", 25], ["Industrial Solvents", 20], ["GENERAL", 23]],
    "Phoenix": [["Semiconductor Wafers", 30], ["Avionics Control Systems", 15], ["GENERAL", 23]],
    "Pine Bluff": [["Heavy Paper Rolls", 40], ["Munitions & Explosives", 15], ["GENERAL", 19]],
    "Pittsburgh": [["Hot-Rolled Steel Coils", 35], ["Structural I-Beams", 25], ["Scrap Steel", 10], ["GENERAL", 13], ["Rebar Bundles", 12]],
    "Pocatello": [["Semiconductor Wafers", 30], ["Grains & Bulk Wheat", 15], ["GENERAL", 23]],
    "Portland": [["Bulk Foreign Textiles", 30], ["Standard Shipping Containers", 20], ["GENERAL", 21]],
    "Portland ME": [["Live Lobsters", 30], ["Diesel Fuel", 20], ["GENERAL", 21]],
    "Price": [["Crushed Coal", 50], ["GENERAL", 21]],
    "Providence": [["Bulk Foreign Textiles", 25], ["Frozen Seafood", 20], ["GENERAL", 23]],
    "Provo": [["Server Rack Cabinets", 20], ["Consumer Laptops & PCs", 20], ["GENERAL", 25]],
    "Pueblo": [["Hot-Rolled Steel Coils", 40], ["Structural I-Beams", 25], ["GENERAL", 15]],
    "Raleigh": [["Refrigerated Vaccines", 30], ["Bottled Prescription Meds", 20], ["GENERAL", 21]],
    "Rapid City": [["Flash-Frozen Beef Quarters", 25], ["Crushed Coal", 15], ["GENERAL", 25]],
    "Reading": [["LTL Mixed Pallets", 30], ["E-Commerce Fulfillment", 20], ["GENERAL", 21]],
    "Redding": [["Raw Pine Logs", 45], ["Milled Lumber Boards", 25], ["GENERAL", 13]],
    "Reno": [["Battery Packs", 35], ["LTL Mixed Pallets", 25], ["GENERAL", 17]],
    "Richmond": [["LTL Mixed Pallets", 25], ["E-Commerce Fulfillment", 20], ["GENERAL", 23]],
    "Riverside": [["E-Commerce Fulfillment", 35], ["Fresh Citrus Fruits", 25], ["GENERAL", 17]],
    "Roanoke": [["LTL Mixed Pallets", 30], ["Hospital Beds", 15], ["GENERAL", 23]],
    "Rochester": [["Semiconductor Wafers", 25], ["Server Rack Cabinets", 15], ["GENERAL", 25]],
    "Rock Springs": [["Crushed Coal", 35], ["Unrefined Crude Oil", 25], ["GENERAL", 17]],
    "Rockford": [["Machined Engine Blocks", 25], ["LTL Mixed Pallets", 25], ["GENERAL", 21]],
    "Sacramento": [["Grains & Bulk Wheat", 25], ["LTL Mixed Pallets", 20], ["GENERAL", 23]],
    "Saginaw": [["Stamped Auto Body Panels", 35], ["Machined Engine Blocks", 20], ["GENERAL", 19]],
    "Salem": [["Fresh Leafy Greens", 30], ["LTL Mixed Pallets", 20], ["GENERAL", 21]],
    "Salina": [["Grains & Bulk Wheat", 45], ["LTL Mixed Pallets", 15], ["GENERAL", 17]],
    "Salisbury": [["Fresh Chicken Breasts", 45], ["Fresh Leafy Greens", 15], ["GENERAL", 17]],
    "Salt Lake City": [["Refined Copper Cathodes", 25], ["Unleaded Gasoline", 20], ["GENERAL", 23]],
    "San Angelo": [["Grains & Bulk Wheat", 35], ["Unrefined Crude Oil", 25], ["GENERAL", 17]],
    "San Antonio": [["Tactical Rations / MREs", 20], ["Armored Vehicle Parts", 10], ["GENERAL", 29]],
    "San Bernardino": [["Amazon Prime Parcels", 40], ["E-Commerce Fulfillment", 25], ["GENERAL", 15]],
    "San Diego": [["Classified Defense Tech", 20], ["Refrigerated Vaccines", 15], ["Standard Shipping Containers", 25], ["GENERAL", 17]],
    "San Francisco": [["Server Rack Cabinets", 25], ["Telecommunications Switches", 15], ["GENERAL", 25]],
    "San Jose": [["Semiconductor Wafers", 35], ["Server Rack Cabinets", 25], ["Consumer Laptops & PCs", 10], ["GENERAL", 13], ["High-End Smartphones", 12]],
    "Santa Rosa": [["Fresh Citrus Fruits", 20], ["Bottled Milk", 15], ["GENERAL", 27]],
    "Savannah": [["Standard Shipping Containers", 40], ["Finished Sedans & Coupes", 20], ["LTL Mixed Pallets", 15], ["GENERAL", 11]],
    "Scottsbluff": [["Baled Hay & Alfalfa", 35], ["Grains & Bulk Wheat", 25], ["GENERAL", 17]],
    "Scranton": [["Heavy Paper Rolls", 35], ["LTL Mixed Pallets", 25], ["GENERAL", 17]],
    "Seattle": [["Jet Engine Turbines", 25], ["Fuselage Skin Panels", 20], ["Server Rack Cabinets", 15], ["GENERAL", 17]],
    "Sheboygan": [["Bulk Cheese Wheels", 30], ["LTL Mixed Pallets", 20], ["GENERAL", 21], ["Artisanal Butter Pallets", 18]],
    "Shreveport": [["Unrefined Crude Oil", 25], ["Milled Lumber Boards", 20], ["GENERAL", 23]],
    "Sioux City": [["Processed Pork Products", 40], ["Grains & Bulk Wheat", 20], ["GENERAL", 17], ["Liquid Fertilizer", 15]],
    "Sioux Falls": [["Flash-Frozen Beef Quarters", 40], ["Processed Pork Products", 20], ["GENERAL", 17]],
    "South Bend": [["Machined Engine Blocks", 30], ["Stamped Auto Body Panels", 20], ["GENERAL", 21]],
    "Spokane": [["Bulk Potatoes", 25], ["Milled Lumber Boards", 20], ["GENERAL", 23]],
    "Springfield MA": [["LTL Mixed Pallets", 30], ["Machined Engine Blocks", 15], ["GENERAL", 23]],
    "Springfield MO": [["LTL Mixed Pallets", 40], ["E-Commerce Fulfillment", 20], ["GENERAL", 17]],
    "St. Joseph": [["Grains & Bulk Wheat", 30], ["Refrigerated Vaccines", 20], ["GENERAL", 21]],
    "St. Louis": [["Refrigerated Vaccines", 20], ["E-Commerce Fulfillment", 15], ["GENERAL", 27]],
    "Stockton": [["Standard Shipping Containers", 35], ["Baled Hay & Alfalfa", 25], ["GENERAL", 17]],
    "Syracuse": [["Surgical Instruments", 25], ["LTL Mixed Pallets", 15], ["GENERAL", 25]],
    "Tacoma": [["Standard Shipping Containers", 45], ["LTL Mixed Pallets", 15], ["GENERAL", 17]],
    "Tallahassee": [["E-Commerce Fulfillment", 20], ["LTL Mixed Pallets", 15], ["GENERAL", 27]],
    "Tampa": [["Standard Shipping Containers", 25], ["Phosphate Rock", 25], ["Armored Vehicle Parts", 10], ["GENERAL", 17]],
    "Texarkana": [["Heavy Paper Rolls", 35], ["Corrugated Cardboard", 25], ["GENERAL", 17]],
    "The Dalles": [["Baled Hay & Alfalfa", 25], ["Fresh Leafy Greens", 20], ["GENERAL", 23]],
    "Toledo": [["Heavy-Duty Pickup Trucks", 40], ["Sheet Metal Stock", 15], ["GENERAL", 19]],
    "Topeka": [["LTL Mixed Pallets", 35], ["Grains & Bulk Wheat", 15], ["GENERAL", 21]],
    "Tucson": [["Refined Copper Cathodes", 35], ["Armored Vehicle Parts", 15], ["GENERAL", 21]],
    "Tulsa": [["Jet Engine Turbines", 25], ["Diesel Fuel", 25], ["GENERAL", 21]],
    "Tupelo": [["Milled Lumber Boards", 20], ["Grains & Bulk Wheat", 15], ["GENERAL", 27]],
    "Tuscaloosa": [["Finished Sedans & Coupes", 35], ["Stamped Auto Body Panels", 15], ["GENERAL", 21]],
    "Twin Falls": [["Bulk Potatoes", 35], ["Bottled Milk", 25], ["GENERAL", 17], ["Yogurt Containers", 15]],
    "Valdosta": [["Fresh Leafy Greens", 30], ["Tactical Rations / MREs", 15], ["GENERAL", 23]],
    "Victoria": [["LTL Mixed Pallets", 30], ["Synthetic Polymers", 30], ["GENERAL", 17]],
    "Visalia": [["Bottled Milk", 35], ["Bulk Cheese Wheels", 25], ["Palletized Avocados", 10], ["GENERAL", 13], ["Ice Cream Tubs", 12]],
    "Waco": [["Grains & Bulk Wheat", 25], ["Machined Engine Blocks", 15], ["GENERAL", 25]],
    "Washington": [["Classified Defense Tech", 20], ["Overnight Express Envelopes", 20], ["GENERAL", 25]],
    "Watertown": [["Tactical Rations / MREs", 25], ["Bottled Milk", 15], ["GENERAL", 25]],
    "West Palm Beach": [["Fresh Citrus Fruits", 25], ["Fresh Leafy Greens", 20], ["GENERAL", 23]],
    "Wheeling": [["Hot-Rolled Steel Coils", 35], ["Diesel Fuel", 25], ["GENERAL", 17]],
    "Wichita": [["Fuselage Skin Panels", 40], ["Grains & Bulk Wheat", 20], ["GENERAL", 17], ["Landing Gear Struts", 15]],
    "Wichita Falls": [["Diesel Fuel", 35], ["Grains & Bulk Wheat", 15], ["GENERAL", 21]],
    "Williston": [["Unrefined Crude Oil", 80], ["GENERAL", 8]],
    "Wilmington": [["Standard Shipping Containers", 25], ["LTL Mixed Pallets", 15], ["GENERAL", 25]],
    "Wilmington DE": [["Industrial Solvents", 30], ["Sulfuric Acid", 20], ["GENERAL", 21]],
    "Winchester": [["Washington Apples", 35], ["LTL Mixed Pallets", 25], ["GENERAL", 17]],
    "Winston-Salem": [["Server Rack Cabinets", 20], ["LTL Mixed Pallets", 20], ["GENERAL", 25]],
    "Worcester": [["Refrigerated Vaccines", 25], ["Bottled Prescription Meds", 15], ["GENERAL", 25]],
    "Yakima": [["Washington Apples", 45], ["Fresh Leafy Greens", 20], ["GENERAL", 15]],
    "Youngstown": [["Hot-Rolled Steel Coils", 45], ["Structural I-Beams", 25], ["GENERAL", 13], ["Rebar Bundles", 15]],
    "Yuma": [["Fresh Leafy Greens", 40], ["Tactical Rations / MREs", 10], ["GENERAL", 21]],
};
